export const ProductItems = [
    {
        id: 'GG1',
        name: 'Giày cao gót nữ màu bạc quai đính đá',
        description: 'Mô tả mẫu 1',
        photoURL: '/Juva-1.jpg',
        photoURL2: '/Juva-12.jpg',
        size: ['S', 'M', 'L', 'XL'],
        price: 2000,
    },
    {
        id: 'GN1',
        name: 'Giày cao gót tiểu thư',
        description: 'Mô tả mẫu 2',
        photoURL: '/Juva-2.jpg',
        photoURL2: '/Juva-15.jpg',
        size: ['41', '42', '43', '44'],
        price: 410000,
    },
    {
        id: 'GW4',
        name: 'Giày cao gót đen dây chéo phối dây đá',
        description: 'Mô tả mẫu 3',
        photoURL: '/Juva-3.jpg',
        photoURL2: '/Juva-16.jpg',
        size: ['S', 'M', 'L', 'XL'],
        price: 450000,
    },
    {
        id: 'GB1',
        name: 'Giày cao gót quai sang chảnh',
        description: 'Mô tả mẫu 4',
        photoURL: '/Juva-4.jpg',
        photoURL2: '/Juva-14.jpg',
        size: ['41', '42', '43', '44'],
        price: 410000,
    },
    {
        id: 'GN2',
        name: 'Giày cao gót nude đế trong',
        description: 'Mô tả mẫu 5',
        photoURL: '/Juva-5.jpg',
        photoURL2: '/Juva-13.jpg',
        size: ['S', 'M', 'L', 'XL'],
        price: 410000,
    },
    {
        id: 'GB4',
        name: 'Giày cao gót đen quai đính đá',
        description: 'Mô tả mẫu 6',
        photoURL: '/Juva-6.jpg',
        photoURL2: '/Juva-11.jpg',
        size: ['S', 'M', 'L', 'XL'],
        price: 470000,
    },
    {
        id: 'GB3',
        name: 'Guốc đen sang chảnh đá 7 màu',
        description: 'Mô tả mẫu 7',
        photoURL: '/Juva-7.jpg',
        photoURL2: '/Juva-17.jpg',
        size: ['S', 'M', 'L', 'XL'],
        price: 490000,
    },
    {
        id: 'GB2',
        name: 'Giày cao gót đen quai đính đá',
        description: 'Mô tả mẫu 8',
        photoURL: '/Juva-8.jpg',
        photoURL2: '/Juva-18.jpg',
        size: ['S', 'M', 'L', 'XL'],
        price: 450000,
    },
    {
        id: 'GW2',
        name: 'Giày cao gót trắng quai chéo dây phối dây đá',
        description: 'Mô tả mẫu 9',
        photoURL: '/Juva-9.jpg',
        photoURL2: '/Juva-20.jpg',
        size: ['S', 'M', 'L', 'XL'],
        price: 430000,
    },
    {
        id: 'GW1',
        name: 'Giày cao gót trắng quai chéo đính đá ',
        description: 'Mô tả mẫu 10',
        photoURL: '/Juva-10.jpg',
        photoURL2: '/Juva-19.jpg',
        size: ['S', 'M', 'L', 'XL'],
        price: 430000,
    },
]