export const ProductItems = [
    {
        id: '1',
        name: 'Test Product 1',
        description: 'Nothing to see here',
        photoURL: '/Juva-1.jpg',
        size: ['S', 'M', 'L', 'XL'],
        price: 30000,
    },
    {
        id: '2',
        name: 'Test Product 2',
        description: 'Still nothing to see here',
        photoURL: '/Juva-2.jpg',
        size: ['41', '42', '43', '44'],
        price: 40000,
    },
    {
        id: '3',
        name: 'Test Product 3',
        description: 'Yeah why are you still reading',
        photoURL: '/Juva-3.jpg',
        size: ['S', 'M', 'L', 'XL'],
        price: 50000,
    },
    {
        id: '4',
        name: 'Test Product 4',
        description: 'Stop bro',
        photoURL: '/Juva-4.jpg',
        size: ['41', '42', '43', '44'],
        price: 60000,
    },
    {
        id: '5',
        name: 'Test Product 5',
        description: 'I wont even bother asking',
        photoURL: '/Juva-5.jpg',
        size: ['S', 'M', 'L', 'XL'],
        price: 70000,
    },
    {
        id: '6',
        name: 'Tên mẫu 6',
        description: 'Mô tả mẫu 6',
        photoURL: '/Juva-6.jpg',
        size: ['S', 'M', 'L', 'XL'],
        price: 80000,
    },
    {
        id: '7',
        name: 'Tên mẫu 7',
        description: 'Mô tả mẫu 7',
        photoURL: '/Juva-7.jpg',
        size: ['S', 'M', 'L', 'XL'],
        price: 90000,
    },
    {
        id: '8',
        name: 'Tên mẫu 8',
        description: 'Mô tả mẫu 8',
        photoURL: '/Juva-8.jpg',
        size: ['S', 'M', 'L', 'XL'],
        price: 100000,
    },
    {
        id: '9',
        name: 'Tên mẫu 9',
        description: 'Mô tả mẫu 9',
        photoURL: '/Juva-9.jpg',
        size: ['S', 'M', 'L', 'XL'],
        price: 110000,
    },
    {
        id: '10',
        name: 'Tên mẫu 10',
        description: 'Mô tả mẫu 10',
        photoURL: '/Juva-10.jpg',
        size: ['S', 'M', 'L', 'XL'],
        price: 120000,
    },
]